services:
  backend:
    image: tharukshan/mern-backend:latest
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - mern-network
    depends_on:
      - mongo

  frontend:
    image: tharukshan/mern-frontend:latest
    build:
      context: ./frontend
    ports:
      - "8000:80"
    networks:
      - mern-network
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
